### ISSUE TITLE
No "bounding_box" in loaded scene graphs

### ISSUE THREAD

**Issue by jiadingfang** [MIT-SPARK/Clio#5]
Hi authos,

Thanks for the great work!

I would like to understand the IB method, and tried to run the example command
`python clio_batch/object_cluster.py ~/clio_logs/office/trial_0/large_fine_ps/dsg.json ~/clio_datasets/office/tasks_office.yaml ~/clio_output clio_eval/experiments/configs/cluster/large_delta_00001.yaml`

However, it errors out with
```
Traceback (most recent call last):
  File "/home/fjd/clio/clio_batch/object_cluster.py", line 207, in <module>
    main()
  File "/home/fjd/miniforge3/envs/clio/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/fjd/miniforge3/envs/clio/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/fjd/miniforge3/envs/clio/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fjd/miniforge3/envs/clio/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/fjd/clio/clio_batch/object_cluster.py", line 185, in main
    clustered_G = cluster_3d(str(scene_graph_path), task_file, output_folder,
  File "/home/fjd/clio/clio_batch/object_cluster.py", line 140, in cluster_3d
    nx_graphs = create_cluster_graphs(G_nx, partition, bbox_dilation)
  File "/home/fjd/clio/clio_batch/object_cluster.py", line 35, in create_cluster_graphs
    bboxes = [G_obj_nx.nodes[x]["bounding_box"] for x in G_obj_nx]
  File "/home/fjd/clio/clio_batch/object_cluster.py", line 35, in <listcomp>
    bboxes = [G_obj_nx.nodes[x]["bounding_box"] for x in G_obj_nx]
KeyError: 'bounding_box'
```

I checked the loaded graph, each node comes with the following information
> G_nx.nodes[8286623314361715065]
> {'is_predicted': False, 'last_update_time_ns': 0, 'position': array([-21.10782242,  -2.93993044,  -0.38250542])}

I did check the `clio_logs/office/trial_0/large_fine_ps/dsg.json` and verify it has 'bound_box' as part of its attributes, so it probably is a loading issue using `spark_dsg`. But since it is cpp api, I'm not sure how to change options to load differently.

I installed the repo without ROS, not sure if this is the reason. Appreciate it if you can help.

**Comment by jiadingfang** [comment]
I bypassed the first issue by noticing that the graph already has edges, so it does not need to use bbox for that purpose. However,  it still errors out with the following error:

> Traceback (most recent call last):
>   File "/home/fjd/clio/clio_batch/object_cluster.py", line 216, in <module>
>     main()
>   File "/home/fjd/miniforge3/envs/clio/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/fjd/miniforge3/envs/clio/lib/python3.9/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)
>   File "/home/fjd/miniforge3/envs/clio/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/fjd/miniforge3/envs/clio/lib/python3.9/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)
>   File "/home/fjd/clio/clio_batch/object_cluster.py", line 194, in main
>     clustered_G = cluster_3d(str(scene_graph_path), task_file, output_folder,
>   File "/home/fjd/clio/clio_batch/object_cluster.py", line 157, in cluster_3d
>     cluster_assignments += cluster_objects(
>   File "/home/fjd/clio/clio_batch/object_cluster.py", line 70, in cluster_objects
>     [np.average(cluster_nx.nodes[x]["semantic_feature"], axis=1) for x in cluster_nx])
>   File "/home/fjd/clio/clio_batch/object_cluster.py", line 70, in <listcomp>
>     [np.average(cluster_nx.nodes[x]["semantic_feature"], axis=1) for x in cluster_nx])
> KeyError: 'semantic_feature'

**Comment by Dominic101** [comment]
The python code for Clio-batch does not need ROS so that is not the issue. Are you sure you installed spark_dsg from the develop branch?

**Comment by jiadingfang** [comment]
The original `pyproject.toml` has the line "spark_dsg@git+https://github.com/MIT-SPARK/Spark-DSG.git#devel", but the develop branch at Spark-DSG is actually named `develop`. Changing the name and re-install the Spark-DSG repo solves this issue. Thanks!

**Comment by Dominic101** [comment]
Thanks for catching this! I pushed the fix to pyproject.toml

**Comment by WentingXu3o3** [comment]
> The original `pyproject.toml` has the line "spark_dsg@git+https://github.com/MIT-SPARK/Spark-DSG.git#devel", but the develop branch at Spark-DSG is actually named `develop`. Changing the name and re-install the Spark-DSG repo solves this issue. Thanks!

Hi Jiading, I reinstalled spark-dsg with "spark_dsg@git+https://github.com/MIT-SPARK/Spark-DSG.git#develop", and run the code but it seems like still could not find "boudningbox". I check the networkx.py in clio/lib/python3.8/site-packages/spark_dsg/ where the "_convert_attr" module clearly loses "bounding box" from dir(attrs) to get the valid_fields. Have you met the same issue?

**Comment by Laura-Ting** [comment]
> > The original `pyproject.toml` has the line "spark_dsg@git+https://github.com/MIT-SPARK/Spark-DSG.git#devel", but the develop branch at Spark-DSG is actually named `develop`. Changing the name and re-install the Spark-DSG repo solves this issue. Thanks!
> 
> Hi Jiading, I reinstalled spark-dsg with "spark_dsg@git+https://github.com/MIT-SPARK/Spark-DSG.git#develop", and run the code but it seems like still could not find "boudningbox". I check the networkx.py in clio/lib/python3.8/site-packages/spark_dsg/ where the "_convert_attr" module clearly loses "bounding box" from dir(attrs) to get the valid_fields. Have you met the same issue?

Hi,
I found that after running a `pip install -e .` in dir `spark_dsg` could solve the same problem for me.
