### ISSUE TITLE
When run python clio_batch/object_cluster.py, no "bounding_box"!

### ISSUE THREAD

**Issue by WentingXu3o3** [MIT-SPARK/Clio#6]
Hi,
In object_cluster.py, when running to create_cluster_graphs module, I met an keyError with 'bounding_box'. The keys in G_obj_nx.nodes[x] are 'is_predicted', 'last_updae_time_ns' and 'position' as I printed. I try to see what has been built with DynamicSceneGraph model in spark_dsg._dsg_bindings. But I cannot find its definition.

I can see from the original dsg.json file, there is 'bounding_box' key in 'attribute', but I don't think it been kept with dsg.DynamicSceneGraph.load().

Any help would be appreciated. Cheers.

**Comment by Dominic101** [comment]
This is because the spark_dsg dependency was not installed from the develop branch (see #5). If you switch to the develop branch on SparkDSG and install, it should work.  I've just pushed the fix to pyproject.toml  which should automatically do this as well.

**Comment by WentingXu3o3** [comment]
Thank you!
